"use strict";
exports.__esModule = true;
exports.LOAD_TODOS_SUCCESS = 'App/LOAD_TODOS_SUCCESS';
exports.ADD_TODOS = 'App/ADD_TODOS';
exports.REFRESHING_TODOS = 'App/REFRESHING_TODOS';
exports.TASK_TITLE_CHANGED = 'App/TASK_TITLE_CHANGED';
exports.EDIT_TODOS = 'App/EDIT_TODOS';
exports.DELETE_TODOS = 'App/DELETE_TODOS';
exports.CHANGE_TODO_TYPE = 'App/CHANGE_TODO_TYPE';
exports.REHYDRATE = 'persist/REHYDRATE';
